version: '3.8'

services:
  gateway:
    container_name: incidents-gateway
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./logs:/usr/src/app/logs
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - HOST=localhost
      - PORT=4000
      - AUTH_HOST=host.docker.internal
      - AUTH_PORT=5555
      - MARKS_HOST=host.docker.internal
      - MARKS_PORT=4444
      - RMQ_HOST=amqp://localhost:5672
    depends_on:
      - redis

  redis:
    container_name: incidents-redis
    image: "redis:latest"
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data:/data

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"  # port for clients
      - "15672:15672" # port for web ui
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin


