export enum MsgAuthEnum {
  ME = 'me',
  SIGNIN = 'signin',
  SIGNUP = 'signup',
  LOGOUT = 'logout',
  REFRESH = 'refresh',
  AUTH = 'auth',
  DELETE = 'delete',
  USER_ROLES = 'user-roles',
  GOOGLE_AUTH = 'google-auth',
  JWT_AUTH = 'jwt-auth',
  YANDEX_AUTH = 'yandex-auth',
  ADMIN_LOGIN = 'admin-login',
  GET_ALL_USERS = 'get-all-users',
  BLOCK_USER = 'block-user',
  UNBLOCK_USER = 'unblock-user',
  UPDATE_ADMIN = 'update-admin',
  CREATE_USER_BY_ADMIN = 'create-user-by-admin',
  ADD_ADMIN_ROLE_TO_USER = 'add-admin-role-to-user',
  USERS_STATS = 'users-stats',
}
